### ISSUE TITLE
Beta Launch Checklist

### ISSUE THREAD

**Issue by atrain440** [GSA/innovation.gov#59]
**Innovation.gov**
- [ ] Check to see all feedback surveys work
- [ ] Incorporate surveys into code
- [ ] Challenge or Competition? Make a decision and then go with it for the site
- [ ] Update subscribe links in code
- [ ] Push I.gov live (no announcement until Thursday)
- [ ] Index I.gov pages through Search.gov
- [ ] Test to see if Search and DAP is working

**Other info**
- [ ] Review Newsletter for content; update it
- [ ]
